import PageTemplate from '~/components/PageTemplate'

export default function Home() {
  return (
    <PageTemplate title='Home'>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Egestas purus viverra accumsan in nisl nisi scelerisque. Sit amet volutpat consequat mauris nunc congue nisi. Dictum varius duis at consectetur lorem donec massa sapien. Eu augue ut lectus arcu bibendum at varius vel. Scelerisque fermentum dui faucibus in ornare. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Eros in cursus turpis massa tincidunt. Odio aenean sed adipiscing diam donec adipiscing tristique risus. Vitae aliquet nec ullamcorper sit amet risus nullam. Eget lorem dolor sed viverra ipsum nunc aliquet. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Platea dictumst vestibulum rhoncus est pellentesque elit. Egestas sed tempus urna et pharetra pharetra massa. Elit ut aliquam purus sit amet luctus venenatis. Elit duis
        tristique sollicitudin nibh sit amet commodo. At consectetur lorem donec massa. Duis convallis convallis tellus id interdum velit. Mauris augue neque gravida in fermentum et sollicitudin. Viverra mauris in aliquam sem. Arcu non sodales neque sodales ut etiam sit. Quam nulla porttitor massa id neque. Ut pharetra sit amet aliquam id diam maecenas ultricies. Est ultricies integer quis auctor elit. Montes nascetur ridiculus mus mauris vitae. Viverra ipsum nunc aliquet bibendum. Sed nisi lacus sed viverra tellus in hac habitasse platea. Cursus in hac habitasse platea dictumst quisque. Tempus imperdiet nulla malesuada pellentesque elit. Purus semper eget duis at tellus. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Convallis convallis tellus id interdum velit laoreet id donec. Vulputate ut pharetra sit amet aliquam. Diam maecenas ultricies mi eget mauris pharetra et. Ut venenatis tellus in metus vulputate eu. Vulputate eu scelerisque felis imperdiet. Adipiscing
        diam donec adipiscing tristique risus nec feugiat in. Faucibus interdum posuere lorem ipsum. Id venenatis a condimentum vitae sapien pellentesque. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Sed vulputate mi sit amet. Ultricies tristique nulla aliquet enim tortor at. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Ipsum dolor sit amet consectetur. Vulputate dignissim suspendisse in est. Mauris augue neque gravida in fermentum. Aliquam purus sit amet luctus. Eros donec ac odio tempor orci. Id venenatis a condimentum vitae sapien. Vulputate ut pharetra sit amet aliquam. Eu mi bibendum neque egestas congue quisque. Vitae suscipit tellus mauris a diam. Neque sodales ut etiam sit amet nisl purus. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Pretium quam vulputate dignissim suspendisse. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Aliquet nibh praesent tristique magna sit amet. Risus commodo viverra
        maecenas accumsan lacus. Rhoncus urna neque viverra justo nec ultrices dui. Quam lacus suspendisse faucibus interdum. Donec ultrices tincidunt arcu non. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Sit amet venenatis urna cursus eget nunc. Non quam lacus suspendisse faucibus interdum. At varius vel pharetra vel turpis nunc eget.
      </div>
    </PageTemplate>
  )
}
